-- AlterTable
ALTER TABLE "Agent" ADD COLUMN     "autoReschedule" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "endpointingMs" INTEGER,
ADD COLUMN     "finalCallMessage" TEXT,
ADD COLUMN     "interruptWords" INTEGER,
ADD COLUMN     "language" TEXT,
ADD COLUMN     "maxCallDuration" INTEGER,
ADD COLUMN     "noiseCancellation" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "responseLatency" INTEGER,
ADD COLUMN     "silenceTimeout" INTEGER,
ADD COLUMN     "similarityBoost" DOUBLE PRECISION,
ADD COLUMN     "speechRate" DOUBLE PRECISION,
ADD COLUMN     "stability" DOUBLE PRECISION,
ADD COLUMN     "sttModel" TEXT,
ADD COLUMN     "styleExaggeration" DOUBLE PRECISION,
ADD COLUMN     "telephonyProvider" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "voicemailDetection" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "voice" DROP NOT NULL,
ALTER COLUMN "temperature" DROP NOT NULL;
